In [1]:
#phase - 0
!pip install pandas numpy scikit-learn matplotlib seaborn flask ultralytics opencv-python streamlit

Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: pandas in C:\Users\ujwal\AppData\Roaming\Python\Python314\site-packages (3.0.5)
Requirement already satisfied: numpy in C:\Users\ujwal\AppData\Roaming\Python\Python314\site-packages (2.5.1)
Requirement already satisfied: scikit-learn in C:\Users\ujwal\AppData\Roaming\Python\Python314\site-packages (1.9.0)
Requirement already satisfied: matplotlib in C:\Users\ujwal\AppData\Roaming\Python\Python314\site-packages (3.11.1)
Requirement already satisfied: seaborn in C:\Users\ujwal\AppData\Roaming\Python\Python314\site-packages (0.13.2)
Requirement already satisfied: flask in C:\Users\ujwal\AppData\Roaming\Python\Python314\site-packages (3.1.3)
Requirement already satisfied: ultralytics in C:\Users\ujwal\AppData\Roaming\Python\Python314\site-packages (8.4.135)
Requirement already satisfied: opencv-python in C:\Users\ujwal\AppData\Roaming\Python\Python314\site-packages (5.0.0.93)
Requirement already satisfied: streamlit in C:\Users\ujwal\AppData\Roaming\Python\Python314\site-packages (1.62.0)
Requirement already satisfied: python-dateutil>=2.8.2 in C:\Users\ujwal\AppData\Roaming\Python\Python314\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: tzdata in C:\Users\ujwal\AppData\Roaming\Python\Python314\site-packages (from pandas) (2026.3)
Requirement already satisfied: scipy>=1.10.0 in C:\Users\ujwal\AppData\Roaming\Python\Python314\site-packages (from scikit-learn) (1.18.1)
Requirement already satisfied: joblib>=1.4.0 in C:\Users\ujwal\AppData\Roaming\Python\Python314\site-packages (from scikit-learn) (1.5.3)
Requirement already satisfied: narwhals>=2.0.1 in C:\Users\ujwal\AppData\Roaming\Python\Python314\site-packages (from scikit-learn) (2.25.0)
Requirement already satisfied: threadpoolctl>=3.5.0 in C:\Users\ujwal\AppData\Roaming\Python\Python314\site-packages (from scikit-learn) (3.6.0)
Requirement already satisfied: contourpy>=1.0.1 in C:\Users\ujwal\AppData\Roaming\Python\Python314\site-packages (from matplotlib) (1.3.3)
Requirement already satisfied: cycler>=0.10 in C:\Users\ujwal\AppData\Roaming\Python\Python314\site-packages (from matplotlib) (0.12.1)
Requirement already satisfied: fonttools>=4.28.2 in C:\Users\ujwal\AppData\Roaming\Python\Python314\site-packages (from matplotlib) (4.63.0)
Requirement already satisfied: kiwisolver>=1.3.1 in C:\Users\ujwal\AppData\Roaming\Python\Python314\site-packages (from matplotlib) (1.5.0)
Requirement already satisfied: packaging>=20.0 in C:\Users\ujwal\AppData\Roaming\Python\Python314\site-packages (from matplotlib) (26.3)
Requirement already satisfied: pillow>=9 in C:\Users\ujwal\AppData\Roaming\Python\Python314\site-packages (from matplotlib) (12.3.0)
Requirement already satisfied: pyparsing>=3 in C:\Users\ujwal\AppData\Roaming\Python\Python314\site-packages (from matplotlib) (3.3.2)
Requirement already satisfied: blinker>=1.9.0 in C:\Users\ujwal\AppData\Roaming\Python\Python314\site-packages (from flask) (1.9.0)
Requirement already satisfied: click>=8.1.3 in C:\Users\ujwal\AppData\Roaming\Python\Python314\site-packages (from flask) (8.5.0)
Requirement already satisfied: itsdangerous>=2.2.0 in C:\Users\ujwal\AppData\Roaming\Python\Python314\site-packages (from flask) (2.2.0)
Requirement already satisfied: jinja2>=3.1.2 in C:\Users\ujwal\AppData\Roaming\Python\Python314\site-packages (from flask) (3.1.6)
Requirement already satisfied: markupsafe>=2.1.1 in C:\Users\ujwal\AppData\Roaming\Python\Python314\site-packages (from flask) (3.0.3)
Requirement already satisfied: werkzeug>=3.1.0 in C:\Users\ujwal\AppData\Roaming\Python\Python314\site-packages (from flask) (3.1.8)
Requirement already satisfied: filelock>=3.16.1 in C:\Users\ujwal\AppData\Roaming\Python\Python314\site-packages (from ultralytics) (3.32.4)
Requirement already satisfied: pyyaml>=5.3.1 in C:\Users\ujwal\AppData\Roaming\Python\Python314\site-packages (from ultralytics) (6.0.3)
Requirement already satisfied: requests>=2.23.0 in C:\Users\ujwal\AppData\Roaming\Python\Python314\site-packages (from ultralytics) (2.34.2)
Requirement already satisfied: torch>=1.8.0 in C:\Users\ujwal\AppData\Roaming\Python\Python314\site-packages (from ultralytics) (2.13.0)
Requirement already satisfied: torchvision>=0.9.0 in C:\Users\ujwal\AppData\Roaming\Python\Python314\site-packages (from ultralytics) (0.28.0)
Requirement already satisfied: psutil>=5.8.0 in C:\Users\ujwal\AppData\Roaming\Python\Python314\site-packages (from ultralytics) (7.2.2)
Requirement already satisfied: polars>=0.20.0 in C:\Users\ujwal\AppData\Roaming\Python\Python314\site-packages (from ultralytics) (1.44.1)
Requirement already satisfied: nvidia-ml-py>=12.0.0 in C:\Users\ujwal\AppData\Roaming\Python\Python314\site-packages (from ultralytics) (13.610.43)
Requirement already satisfied: ultralytics-thop>=2.1.6 in C:\Users\ujwal\AppData\Roaming\Python\Python314\site-packages (from ultralytics) (2.1.6)
Requirement already satisfied: ultralytics-platform>=0.1.3 in C:\Users\ujwal\AppData\Roaming\Python\Python314\site-packages (from ultralytics) (0.1.20)
Requirement already satisfied: altair!=5.4.0,!=5.4.1,<7,>=5.0.0 in C:\Users\ujwal\AppData\Roaming\Python\Python314\site-packages (from streamlit) (6.2.2)
Requirement already satisfied: pydeck<1,>=0.8.0b4 in C:\Users\ujwal\AppData\Roaming\Python\Python314\site-packages (from streamlit) (0.9.3)
Requirement already satisfied: protobuf<8,>=5.26.1 in C:\Users\ujwal\AppData\Roaming\Python\Python314\site-packages (from streamlit) (5.29.6)
Requirement already satisfied: pyarrow!=25.0.0,<26,>=7.0 in C:\Users\ujwal\AppData\Roaming\Python\Python314\site-packages (from streamlit) (25.0.1)
Requirement already satisfied: toml<2,>=0.10.1 in C:\Users\ujwal\AppData\Roaming\Python\Python314\site-packages (from streamlit) (0.10.2)
Requirement already satisfied: typing-extensions<5,>=4.10.0 in C:\Users\ujwal\AppData\Roaming\Python\Python314\site-packages (from streamlit) (4.16.0)
Requirement already satisfied: starlette<2,>=0.46.0 in C:\Users\ujwal\AppData\Roaming\Python\Python314\site-packages (from streamlit) (1.6.0)
Requirement already satisfied: uvicorn<1,>=0.30.0 in C:\Users\ujwal\AppData\Roaming\Python\Python314\site-packages (from streamlit) (0.52.4)
Requirement already satisfied: httptools<1,>=0.6.3 in C:\Users\ujwal\AppData\Roaming\Python\Python314\site-packages (from streamlit) (0.8.0)
Requirement already satisfied: anyio<5,>=4.0.0 in C:\Users\ujwal\AppData\Roaming\Python\Python314\site-packages (from streamlit) (4.14.2)
Requirement already satisfied: python-multipart<1,>=0.0.10 in C:\Users\ujwal\AppData\Roaming\Python\Python314\site-packages (from streamlit) (0.0.32)
Requirement already satisfied: websockets<17,>=12.0.0 in C:\Users\ujwal\AppData\Roaming\Python\Python314\site-packages (from streamlit) (16.1.1)
Requirement already satisfied: watchdog<7,>=2.1.5 in C:\Users\ujwal\AppData\Roaming\Python\Python314\site-packages (from streamlit) (6.0.0)
Requirement already satisfied: jsonschema>=3.0 in C:\Users\ujwal\AppData\Roaming\Python\Python314\site-packages (from altair!=5.4.0,!=5.4.1,<7,>=5.0.0->streamlit) (4.26.0)
Requirement already satisfied: idna>=2.8 in C:\Users\ujwal\AppData\Roaming\Python\Python314\site-packages (from anyio<5,>=4.0.0->streamlit) (3.18)
Requirement already satisfied: charset_normalizer<4,>=2 in C:\Users\ujwal\AppData\Roaming\Python\Python314\site-packages (from requests>=2.23.0->ultralytics) (3.5.0)
Requirement already satisfied: urllib3<3,>=1.26 in C:\Users\ujwal\AppData\Roaming\Python\Python314\site-packages (from requests>=2.23.0->ultralytics) (2.7.0)
Requirement already satisfied: certifi>=2023.5.7 in C:\Users\ujwal\AppData\Roaming\Python\Python314\site-packages (from requests>=2.23.0->ultralytics) (2026.7.22)
Requirement already satisfied: h11>=0.8 in C:\Users\ujwal\AppData\Roaming\Python\Python314\site-packages (from uvicorn<1,>=0.30.0->streamlit) (0.16.0)
Requirement already satisfied: attrs>=22.2.0 in C:\Users\ujwal\AppData\Roaming\Python\Python314\site-packages (from jsonschema>=3.0->altair!=5.4.0,!=5.4.1,<7,>=5.0.0->streamlit) (26.1.0)
Requirement already satisfied: jsonschema-specifications>=2023.03.6 in C:\Users\ujwal\AppData\Roaming\Python\Python314\site-packages (from jsonschema>=3.0->altair!=5.4.0,!=5.4.1,<7,>=5.0.0->streamlit) (2025.9.1)
Requirement already satisfied: referencing>=0.28.4 in C:\Users\ujwal\AppData\Roaming\Python\Python314\site-packages (from jsonschema>=3.0->altair!=5.4.0,!=5.4.1,<7,>=5.0.0->streamlit) (0.37.0)
Requirement already satisfied: rpds-py>=0.25.0 in C:\Users\ujwal\AppData\Roaming\Python\Python314\site-packages (from jsonschema>=3.0->altair!=5.4.0,!=5.4.1,<7,>=5.0.0->streamlit) (2026.6.3)
Requirement already satisfied: polars-runtime-32==1.44.1 in C:\Users\ujwal\AppData\Roaming\Python\Python314\site-packages (from polars>=0.20.0->ultralytics) (1.44.1)
Requirement already satisfied: six>=1.5 in C:\Users\ujwal\AppData\Roaming\Python\Python314\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Requirement already satisfied: setuptools>=77.0.3 in C:\Users\ujwal\AppData\Roaming\Python\Python314\site-packages (from torch>=1.8.0->ultralytics) (84.0.0)
Requirement already satisfied: sympy>=1.13.3 in C:\Users\ujwal\AppData\Roaming\Python\Python314\site-packages (from torch>=1.8.0->ultralytics) (1.14.0)
Requirement already satisfied: networkx>=2.5.1 in C:\Users\ujwal\AppData\Roaming\Python\Python314\site-packages (from torch>=1.8.0->ultralytics) (3.6.1)
Requirement already satisfied: fsspec>=0.8.5 in C:\Users\ujwal\AppData\Roaming\Python\Python314\site-packages (from torch>=1.8.0->ultralytics) (2026.7.0)
Requirement already satisfied: mpmath<1.4,>=1.1.0 in C:\Users\ujwal\AppData\Roaming\Python\Python314\site-packages (from sympy>=1.13.3->torch>=1.8.0->ultralytics) (1.3.0)
Requirement already satisfied: httpx<1,>=0.28 in C:\Users\ujwal\AppData\Roaming\Python\Python314\site-packages (from ultralytics-platform>=0.1.3->ultralytics) (0.28.1)
Requirement already satisfied: httpcore==1.* in C:\Users\ujwal\AppData\Roaming\Python\Python314\site-packages (from httpx<1,>=0.28->ultralytics-platform>=0.1.3->ultralytics) (1.0.9)

In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import sklearn
import cv2
import flask
import streamlit
from ultralytics import YOLO

In [3]:
df = pd.read_csv('dataset_traffic_accident_prediction1.csv')  
print(df.shape) 
print(df.columns.tolist()) 
df.head()

(840, 14)
['Weather', 'Road_Type', 'Time_of_Day', 'Traffic_Density', 'Speed_Limit', 'Number_of_Vehicles', 'Driver_Alcohol', 'Accident_Severity', 'Road_Condition', 'Vehicle_Type', 'Driver_Age', 'Driver_Experience', 'Road_Light_Condition', 'Accident']

,Weather,Road_Type,Time_of_Day,Traffic_Density,Speed_Limit,Number_of_Vehicles,Driver_Alcohol,Accident_Severity,Road_Condition,Vehicle_Type,Driver_Age,Driver_Experience,Road_Light_Condition,Accident
0,Rainy,City Road,Morning,1.0,100.0,5.0,0.0,NaN,Wet,Car,51.0,48.0,Artificial Light,0.0
1,Clear,Rural Road,Night,NaN,120.0,3.0,0.0,Moderate,Wet,Truck,49.0,43.0,Artificial Light,0.0
2,Rainy,Highway,Evening,1.0,60.0,4.0,0.0,Low,Icy,Car,54.0,52.0,Artificial Light,0.0
3,Clear,City Road,Afternoon,2.0,60.0,3.0,0.0,Low,Under Construction,Bus,34.0,31.0,Daylight,0.0
4,Rainy,Highway,Morning,1.0,195.0,11.0,0.0,Low,Dry,Car,62.0,55.0,Artificial Light,1.0

In [4]:
print(df['Accident'].value_counts()) 
print(df['Accident'].value_counts(normalize=True) * 100)

Accident
0.0    559
1.0    239
Name: count, dtype: int64
Accident
0.0    70.050125
1.0    29.949875
Name: proportion, dtype: float64

In [5]:
print(df.isnull().sum())

Weather                 42
Road_Type               42
Time_of_Day             42
Traffic_Density         42
Speed_Limit             42
Number_of_Vehicles      42
Driver_Alcohol          42
Accident_Severity       42
Road_Condition          42
Vehicle_Type            42
Driver_Age              42
Driver_Experience       42
Road_Light_Condition    42
Accident                42
dtype: int64

In [6]:
print(df[df.isnull().all(axis=1)].shape)

(0, 14)

In [7]:
print(df[df.isnull().any(axis=1)].shape)

(435, 14)

In [8]:
df = df.dropna(subset=['Accident'])
print(df.shape)

(798, 14)

In [9]:
print(df.isnull().sum())

Weather                 40
Road_Type               40
Time_of_Day             38
Traffic_Density         40
Speed_Limit             41
Number_of_Vehicles      38
Driver_Alcohol          40
Accident_Severity       42
Road_Condition          41
Vehicle_Type            39
Driver_Age              40
Driver_Experience       41
Road_Light_Condition    40
Accident                 0
dtype: int64

In [10]:
numeric_cols = ['Traffic_Density', 'Speed_Limit', 'Number_of_Vehicles', 'Driver_Age', 'Driver_Experience']
for col in numeric_cols:
    df[col] = df[col].fillna(df[col].median())


categorical_cols = ['Weather', 'Road_Type', 'Time_of_Day', 'Driver_Alcohol', 'Road_Condition', 'Vehicle_Type', 'Road_Light_Condition']
for col in categorical_cols:
    df[col] = df[col].fillna(df[col].mode()[0])

print(df.isnull().sum())

Weather                  0
Road_Type                0
Time_of_Day              0
Traffic_Density          0
Speed_Limit              0
Number_of_Vehicles       0
Driver_Alcohol           0
Accident_Severity       42
Road_Condition           0
Vehicle_Type             0
Driver_Age               0
Driver_Experience        0
Road_Light_Condition     0
Accident                 0
dtype: int64

In [11]:
categorical_cols = ['Weather', 'Road_Type', 'Time_of_Day', 'Driver_Alcohol', 'Road_Condition', 'Vehicle_Type', 'Road_Light_Condition']

df_encoded = pd.get_dummies(df, columns=categorical_cols, drop_first=True)
print(df_encoded.shape)
df_encoded.head()

(798, 26)

,Traffic_Density,Speed_Limit,Number_of_Vehicles,Accident_Severity,Driver_Age,Driver_Experience,Accident,Weather_Foggy,Weather_Rainy,Weather_Snowy,...,Time_of_Day_Night,Driver_Alcohol_1.0,Road_Condition_Icy,Road_Condition_Under Construction,Road_Condition_Wet,Vehicle_Type_Car,Vehicle_Type_Motorcycle,Vehicle_Type_Truck,Road_Light_Condition_Daylight,Road_Light_Condition_No Light
0,1.0,100.0,5.0,NaN,51.0,48.0,0.0,False,True,False,...,False,False,False,False,True,True,False,False,False,False
1,1.0,120.0,3.0,Moderate,49.0,43.0,0.0,False,False,False,...,True,False,False,False,True,False,False,True,False,False
2,1.0,60.0,4.0,Low,54.0,52.0,0.0,False,True,False,...,False,False,True,False,False,True,False,False,False,False
3,2.0,60.0,3.0,Low,34.0,31.0,0.0,False,False,False,...,False,False,False,True,False,False,False,False,True,False
4,1.0,195.0,11.0,Low,62.0,55.0,1.0,False,True,False,...,False,False,False,False,False,True,False,False,False,False

In [12]:
##phase - 1
df_model = df_encoded.drop(columns=['Accident_Severity'])
print(df_model.shape)
df_model.columns.tolist()

(798, 25)

['Traffic_Density',
 'Speed_Limit',
 'Number_of_Vehicles',
 'Driver_Age',
 'Driver_Experience',
 'Accident',
 'Weather_Foggy',
 'Weather_Rainy',
 'Weather_Snowy',
 'Weather_Stormy',
 'Road_Type_Highway',
 'Road_Type_Mountain Road',
 'Road_Type_Rural Road',
 'Time_of_Day_Evening',
 'Time_of_Day_Morning',
 'Time_of_Day_Night',
 'Driver_Alcohol_1.0',
 'Road_Condition_Icy',
 'Road_Condition_Under Construction',
 'Road_Condition_Wet',
 'Vehicle_Type_Car',
 'Vehicle_Type_Motorcycle',
 'Vehicle_Type_Truck',
 'Road_Light_Condition_Daylight',
 'Road_Light_Condition_No Light']

In [13]:
X = df_model.drop(columns=['Accident'])
y = df_model['Accident']

print(X.shape)
print(y.shape)

(798, 24)
(798,)

In [14]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42, stratify=y
)

print(X_train.shape, X_test.shape)
print(y_train.value_counts())
print(y_test.value_counts())

(638, 24) (160, 24)
Accident
0.0    447
1.0    191
Name: count, dtype: int64
Accident
0.0    112
1.0     48
Name: count, dtype: int64

In [15]:
from sklearn.ensemble import RandomForestClassifier

model = RandomForestClassifier(n_estimators=100, random_state=42)
model.fit(X_train, y_train)

print("Model trained successfully")

Model trained successfully

In [16]:
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

y_pred = model.predict(X_test)

print("Accuracy:", accuracy_score(y_test, y_pred))
print("\nClassification Report:\n", classification_report(y_test, y_pred))
print("\nConfusion Matrix:\n", confusion_matrix(y_test, y_pred))

Accuracy: 0.73125

Classification Report:
               precision    recall  f1-score   support

         0.0       0.72      1.00      0.84       112
         1.0       1.00      0.10      0.19        48

    accuracy                           0.73       160
   macro avg       0.86      0.55      0.51       160
weighted avg       0.81      0.73      0.64       160


Confusion Matrix:
 [[112   0]
 [ 43   5]]

In [17]:
from sklearn.ensemble import RandomForestClassifier

model = RandomForestClassifier(n_estimators=100, random_state=42, class_weight='balanced')
model.fit(X_train, y_train)

y_pred = model.predict(X_test)

print("Accuracy:", accuracy_score(y_test, y_pred))
print("\nClassification Report:\n", classification_report(y_test, y_pred))
print("\nConfusion Matrix:\n", confusion_matrix(y_test, y_pred))

Accuracy: 0.68125

Classification Report:
               precision    recall  f1-score   support

         0.0       0.73      0.88      0.79       112
         1.0       0.44      0.23      0.30        48

    accuracy                           0.68       160
   macro avg       0.58      0.55      0.55       160
weighted avg       0.64      0.68      0.65       160


Confusion Matrix:
 [[98 14]
 [37 11]]

In [18]:
y_probs = model.predict_proba(X_test)[:, 1]  

threshold = 0.3
y_pred_adjusted = (y_probs >= threshold).astype(int)

print("Accuracy:", accuracy_score(y_test, y_pred_adjusted))
print("\nClassification Report:\n", classification_report(y_test, y_pred_adjusted))
print("\nConfusion Matrix:\n", confusion_matrix(y_test, y_pred_adjusted))

Accuracy: 0.43125

Classification Report:
               precision    recall  f1-score   support

         0.0       0.76      0.28      0.41       112
         1.0       0.32      0.79      0.46        48

    accuracy                           0.43       160
   macro avg       0.54      0.53      0.43       160
weighted avg       0.63      0.43      0.42       160


Confusion Matrix:
 [[31 81]
 [10 38]]

In [19]:
threshold = 0.4
y_pred_adjusted = (y_probs >= threshold).astype(int)

print("Accuracy:", accuracy_score(y_test, y_pred_adjusted))
print("\nClassification Report:\n", classification_report(y_test, y_pred_adjusted))
print("\nConfusion Matrix:\n", confusion_matrix(y_test, y_pred_adjusted))

Accuracy: 0.6

Classification Report:
               precision    recall  f1-score   support

         0.0       0.77      0.62      0.68       112
         1.0       0.39      0.56      0.46        48

    accuracy                           0.60       160
   macro avg       0.58      0.59      0.57       160
weighted avg       0.65      0.60      0.62       160


Confusion Matrix:
 [[69 43]
 [21 27]]

In [20]:
import joblib

joblib.dump(model, 'accident_risk_model.pkl')
print("Model saved successfully")

Model saved successfully

In [21]:
import os
print(os.getcwd())
print(os.listdir())

c:\Users\ujwal\Downloads\AI_ASS_Project
['accident_risk_model.pkl', 'dataset_traffic_accident_prediction1.csv', 'Phase_0 (Setup).ipynb', 'Phase_0-8.ipynb', 'runs', 'traffic_video.mp4', 'yolov8n.pt']

In [22]:
import os
print(os.listdir())

['accident_risk_model.pkl', 'dataset_traffic_accident_prediction1.csv', 'Phase_0 (Setup).ipynb', 'Phase_0-8.ipynb', 'runs', 'traffic_video.mp4', 'yolov8n.pt']

In [23]:
from ultralytics import YOLO
model_yolo = YOLO('yolov8n.pt')

In [24]:
results = model_yolo('traffic_video.mp4', save=True)
print("Detection complete")

WARNING
Inference results will accumulate in RAM unless `stream=True` is passed, which can cause out-of-memory errors for large
sources or long-running streams and videos. See https://docs.ultralytics.com/modes/predict for help.

Example:
    results = model(source=..., stream=True)  # generator of Results objects
    for r in results:
        boxes = r.boxes  # Boxes object for bbox outputs
        masks = r.masks  # Masks object for segment masks outputs
        probs = r.probs  # Class probabilities for classification outputs

video 1/1 (frame 1/1878) c:\Users\ujwal\Downloads\AI_ASS_Project\traffic_video.mp4: 384x640 1 person, 6 cars, 2 traffic lights, 1 fire hydrant, 172.0ms
video 1/1 (frame 2/1878) c:\Users\ujwal\Downloads\AI_ASS_Project\traffic_video.mp4: 384x640 1 person, 5 cars, 3 traffic lights, 2 fire hydrants, 43.7ms
video 1/1 (frame 3/1878) c:\Users\ujwal\Downloads\AI_ASS_Project\traffic_video.mp4: 384x640 1 person, 8 cars, 3 traffic lights, 1 fire hydrant, 42.5ms
video 1/1 (frame 4/1878) c:\Users\ujwal\Downloads\AI_ASS_Project\traffic_video.mp4: 384x640 2 persons, 7 cars, 5 traffic lights, 43.6ms
video 1/1 (frame 5/1878) c:\Users\ujwal\Downloads\AI_ASS_Project\traffic_video.mp4: 384x640 2 persons, 5 cars, 5 traffic lights, 1 fire hydrant, 48.5ms
video 1/1 (frame 6/1878) c:\Users\ujwal\Downloads\AI_ASS_Project\traffic_video.mp4: 384x640 1 person, 5 cars, 4 traffic lights, 1 fire hydrant, 44.9ms
video 1/1 (frame 7/1878) c:\Users\ujwal\Downloads\AI_ASS_Project\traffic_video.mp4: 384x640 1 person, 5 cars, 2 traffic lights, 44.1ms
video 1/1 (frame 8/1878) c:\Users\ujwal\Downloads\AI_ASS_Project\traffic_video.mp4: 384x640 3 persons, 5 cars, 2 traffic lights, 49.8ms
video 1/1 (frame 9/1878) c:\Users\ujwal\Downloads\AI_ASS_Project\traffic_video.mp4: 384x640 2 persons, 5 cars, 2 traffic lights, 42.1ms
video 1/1 (frame 10/1878) c:\Users\ujwal\Downloads\AI_ASS_Project\traffic_video.mp4: 384x640 1 person, 5 cars, 2 traffic lights, 1 fire hydrant, 44.1ms
video 1/1 (frame 11/1878) c:\Users\ujwal\Downloads\AI_ASS_Project\traffic_video.mp4: 384x640 5 cars, 2 traffic lights, 2 fire hydrants, 50.3ms
video 1/1 (frame 12/1878) c:\Users\ujwal\Downloads\AI_ASS_Project\traffic_video.mp4: 384x640 2 persons, 6 cars, 1 traffic light, 1 fire hydrant, 42.4ms
video 1/1 (frame 13/1878) c:\Users\ujwal\Downloads\AI_ASS_Project\traffic_video.mp4: 384x640 1 person, 7 cars, 2 traffic lights, 42.3ms
video 1/1 (frame 14/1878) c:\Users\ujwal\Downloads\AI_ASS_Project\traffic_video.mp4: 384x640 3 persons, 7 cars, 2 traffic lights, 49.5ms
video 1/1 (frame 15/1878) c:\Users\ujwal\Downloads\AI_ASS_Project\traffic_video.mp4: 384x640 1 person, 9 cars, 1 traffic light, 1 fire hydrant, 46.8ms
video 1/1 (frame 16/1878) c:\Users\ujwal\Downloads\AI_ASS_Project\traffic_video.mp4: 384x640 1 person, 7 cars, 1 fire hydrant, 44.4ms
video 1/1 (frame 17/1878) c:\Users\ujwal\Downloads\AI_ASS_Project\traffic_video.mp4: 384x640 1 person, 7 cars, 47.9ms
video 1/1 (frame 18/1878) c:\Users\ujwal\Downloads\AI_ASS_Project\traffic_video.mp4: 384x640 2 persons, 7 cars, 53.8ms
video 1/1 (frame 19/1878) c:\Users\ujwal\Downloads\AI_ASS_Project\traffic_video.mp4: 384x640 7 cars, 44.7ms
video 1/1 (frame 20/1878) c:\Users\ujwal\Downloads\AI_ASS_Project\traffic_video.mp4: 384x640 7 cars, 1 traffic light, 70.5ms
video 1/1 (frame 21/1878) c:\Users\ujwal\Downloads\AI_ASS_Project\traffic_video.mp4: 384x640 8 cars, 69.8ms
video 1/1 (frame 22/1878) c:\Users\ujwal\Downloads\AI_ASS_Project\traffic_video.mp4: 384x640 9 cars, 41.5ms
video 1/1 (frame 23/1878) c:\Users\ujwal\Downloads\AI_ASS_Project\traffic_video.mp4: 384x640 11 cars, 43.3ms
video 1/1 (frame 24/1878) c:\Users\ujwal\Downloads\AI_ASS_Project\traffic_video.mp4: 384x640 8 cars, 46.0ms
video 1/1 (frame 25/1878) c:\Users\ujwal\Downloads\AI_ASS_Project\traffic_video.mp4: 384x640 1 person, 8 cars, 51.3ms
video 1/1 (frame 26/1878) c:\Users\ujwal\Downloads\AI_ASS_Project\traffic_video.mp4: 384x640 9 cars, 43.3ms
video 1/1 (frame 27/1878) c:\Users\ujwal\Downloads\AI_ASS_Project\traffic_video.mp4: 384x640 11 cars, 70.9ms
video 1/1 (frame 28/1878) c:\Users\ujwal\Downloads\AI_ASS_Project\traffic_video.mp4: 384x640 13 cars, 1 traffic light, 49.6ms
video 1/1 (frame 29/1878) c:\Users\ujwal\Downloads\AI_ASS_Project\traffic_video.mp4: 384x640 10 cars, 42.3ms
video 1/1 (frame 30/1878) c:\Users\ujwal\Downloads\AI_ASS_Project\traffic_video.mp4: 384x640 10 cars, 45.1ms
video 1/1 (frame 31/1878) c:\Users\ujwal\Downloads\AI_ASS_Project\traffic_video.mp4: 384x640 11 cars, 45.7ms
video 1/1 (frame 32/1878) c:\Users\ujwal\Downloads\AI_ASS_Project\traffic_video.mp4: 384x640 10 cars, 46.8ms
video 1/1 (frame 33/1878) c:\Users\ujwal\Downloads\AI_ASS_Project\traffic_video.mp4: 384x640 11 cars, 94.4ms
video 1/1 (frame 34/1878) c:\Users\ujwal\Downloads\AI_ASS_Project\traffic_video.mp4: 384x640 8 cars, 41.5ms
video 1/1 (frame 35/1878) c:\Users\ujwal\Downloads\AI_ASS_Project\traffic_video.mp4: 384x640 9 cars, 41.6ms
video 1/1 (frame 36/1878) c:\Users\ujwal\Downloads\AI_ASS_Project\traffic_video.mp4: 384x640 1 person, 8 cars, 48.1ms
video 1/1 (frame 37/1878) c:\Users\ujwal\Downloads\AI_ASS_Project\traffic_video.mp4: 384x640 1 person, 6 cars, 40.3ms
video 1/1 (frame 38/1878) c:\Users\ujwal\Downloads\AI_ASS_Project\traffic_video.mp4: 384x640 6 cars, 43.5ms
video 1/1 (frame 39/1878) c:\Users\ujwal\Downloads\AI_ASS_Project\traffic_video.mp4: 384x640 6 cars, 52.6ms
video 1/1 (frame 40/1878) c:\Users\ujwal\Downloads\AI_ASS_Project\traffic_video.mp4: 384x640 2 persons, 7 cars, 41.1ms
video 1/1 (frame 41/1878) c:\Users\ujwal\Downloads\AI_ASS_Project\traffic_video.mp4: 384x640 1 person, 6 cars, 46.9ms
video 1/1 (frame 42/1878) c:\Users\ujwal\Downloads\AI_ASS_Project\traffic_video.mp4: 384x640 1 person, 9 cars, 44.4ms
video 1/1 (frame 43/1878) c:\Users\ujwal\Downloads\AI_ASS_Project\traffic_video.mp4: 384x640 5 cars, 39.9ms
video 1/1 (frame 44/1878) c:\Users\ujwal\Downloads\AI_ASS_Project\traffic_video.mp4: 384x640 5 cars, 1 traffic light, 47.3ms
video 1/1 (frame 45/1878) c:\Users\ujwal\Downloads\AI_ASS_Project\traffic_video.mp4: 384x640 5 cars, 46.1ms
video 1/1 (frame 46/1878) c:\Users\ujwal\Downloads\AI_ASS_Project\traffic_video.mp4: 384x640 6 cars, 45.3ms
video 1/1 (frame 47/1878) c:\Users\ujwal\Downloads\AI_ASS_Project\traffic_video.mp4: 384x640 6 cars, 50.5ms
video 1/1 (frame 48/1878) c:\Users\ujwal\Downloads\AI_ASS_Project\traffic_video.mp4: 384x640 1 person, 6 cars, 54.2ms
video 1/1 (frame 49/1878) c:\Users\ujwal\Downloads\AI_ASS_Project\traffic_video.mp4: 384x640 1 person, 6 cars, 41.6ms
video 1/1 (frame 50/1878) c:\Users\ujwal\Downloads\AI_ASS_Project\traffic_video.mp4: 384x640 1 person, 5 cars, 39.9ms
video 1/1 (frame 51/1878) c:\Users\ujwal\Downloads\AI_ASS_Project\traffic_video.mp4: 384x640 5 cars, 45.3ms
video 1/1 (frame 52/1878) c:\Users\ujwal\Downloads\AI_ASS_Project\traffic_video.mp4: 384x640 1 person, 5 cars, 51.0ms
video 1/1 (frame 53/1878) c:\Users\ujwal\Downloads\AI_ASS_Project\traffic_video.mp4: 384x640 1 person, 5 cars, 40.0ms
video 1/1 (frame 54/1878) c:\Users\ujwal\Downloads\AI_ASS_Project\traffic_video.mp4: 384x640 1 person, 6 cars, 40.0ms
video 1/1 (frame 55/1878) c:\Users\ujwal\Downloads\AI_ASS_Project\traffic_video.mp4: 384x640 1 person, 6 cars, 50.7ms
video 1/1 (frame 56/1878) c:\Users\ujwal\Downloads\AI_ASS_Project\traffic_video.mp4: 384x640 1 person, 5 cars, 39.3ms
video 1/1 (frame 57/1878) c:\Users\ujwal\Downloads\AI_ASS_Project\traffic_video.mp4: 384x640 1 person, 7 cars, 39.1ms
video 1/1 (frame 58/1878) c:\Users\ujwal\Downloads\AI_ASS_Project\traffic_video.mp4: 384x640 1 person, 7 cars, 46.0ms
video 1/1 (frame 59/1878) c:\Users\ujwal\Downloads\AI_ASS_Project\traffic_video.mp4: 384x640 1 person, 8 cars, 47.3ms
video 1/1 (frame 60/1878) c:\Users\ujwal\Downloads\AI_ASS_Project\traffic_video.mp4: 384x640 1 person, 7 cars, 45.4ms
video 1/1 (frame 61/1878) c:\Users\ujwal\Downloads\AI_ASS_Project\traffic_video.mp4: 384x640 5 cars, 48.8ms
video 1/1 (frame 62/1878) c:\Users\ujwal\Downloads\AI_ASS_Project\traffic_video.mp4: 384x640 5 cars, 48.4ms
video 1/1 (frame 63/1878) c:\Users\ujwal\Downloads\AI_ASS_Project\traffic_video.mp4: 384x640 1 person, 6 cars, 47.5ms
video 1/1 (frame 64/1878) c:\Users\ujwal\Downloads\AI_ASS_Project\traffic_video.mp4: 384x640 1 person, 6 cars, 38.7ms
video 1/1 (frame 65/1878) c:\Users\ujwal\Downloads\AI_ASS_Project\traffic_video.mp4: 384x640 1 person, 6 cars, 39.3ms
video 1/1 (frame 66/1878) c:\Users\ujwal\Downloads\AI_ASS_Project\traffic_video.mp4: 384x640 1 person, 7 cars, 42.1ms
video 1/1 (frame 67/1878) c:\Users\ujwal\Downloads\AI_ASS_Project\traffic_video.mp4: 384x640 2 persons, 7 cars, 44.0ms
video 1/1 (frame 68/1878) c:\Users\ujwal\Downloads\AI_ASS_Project\traffic_video.mp4: 384x640 2 persons, 7 cars, 42.7ms
video 1/1 (frame 69/1878) c:\Users\ujwal\Downloads\AI_ASS_Project\traffic_video.mp4: 384x640 2 persons, 6 cars, 53.9ms
video 1/1 (frame 70/1878) c:\Users\ujwal\Downloads\AI_ASS_Project\traffic_video.mp4: 384x640 2 persons, 6 cars, 51.5ms
video 1/1 (frame 71/1878) c:\Users\ujwal\Downloads\AI_ASS_Project\traffic_video.mp4: 384x640 2 persons, 5 cars, 44.3ms
video 1/1 (frame 72/1878) c:\Users\ujwal\Downloads\AI_ASS_Project\traffic_video.mp4: 384x640 2 persons, 5 cars, 47.6ms
video 1/1 (frame 73/1878) c:\Users\ujwal\Downloads\AI_ASS_Project\traffic_video.mp4: 384x640 2 persons, 4 cars, 46.5ms
video 1/1 (frame 74/1878) c:\Users\ujwal\Downloads\AI_ASS_Project\traffic_video.mp4: 384x640 1 person, 4 cars, 43.6ms
video 1/1 (frame 75/1878) c:\Users\ujwal\Downloads\AI_ASS_Project\traffic_video.mp4: 384x640 3 persons, 2 bicycles, 4 cars, 48.1ms
video 1/1 (frame 76/1878) c:\Users\ujwal\Downloads\AI_ASS_Project\traffic_video.mp4: 384x640 4 persons, 1 bicycle, 6 cars, 43.9ms
video 1/1 (frame 77/1878) c:\Users\ujwal\Downloads\AI_ASS_Project\traffic_video.mp4: 384x640 1 person, 1 bicycle, 6 cars, 46.8ms
video 1/1 (frame 78/1878) c:\Users\ujwal\Downloads\AI_ASS_Project\traffic_video.mp4: 384x640 4 persons, 1 bicycle, 7 cars, 45.6ms
video 1/1 (frame 79/1878) c:\Users\ujwal\Downloads\AI_ASS_Project\traffic_video.mp4: 384x640 1 person, 7 cars, 46.9ms
video 1/1 (frame 80/1878) c:\Users\ujwal\Downloads\AI_ASS_Project\traffic_video.mp4: 384x640 1 person, 6 cars, 46.1ms
video 1/1 (frame 81/1878) c:\Users\ujwal\Downloads\AI_ASS_Project\traffic_video.mp4: 384x640 6 cars, 45.3ms
video 1/1 (frame 82/1878) c:\Users\ujwal\Downloads\AI_ASS_Project\traffic_video.mp4: 384x640 2 persons, 7 cars, 42.2ms
video 1/1 (frame 83/1878) c:\Users\ujwal\Downloads\AI_ASS_Project\traffic_video.mp4: 384x640 1 person, 6 cars, 44.7ms
video 1/1 (frame 84/1878) c:\Users\ujwal\Downloads\AI_ASS_Project\traffic_video.mp4: 384x640 2 persons, 7 cars, 57.0ms
video 1/1 (frame 85/1878) c:\Users\ujwal\Downloads\AI_ASS_Project\traffic_video.mp4: 384x640 2 persons, 6 cars, 48.0ms
video 1/1 (frame 86/1878) c:\Users\ujwal\Downloads\AI_ASS_Project\traffic_video.mp4: 384x640 1 person, 6 cars, 49.7ms
video 1/1 (frame 87/1878) c:\Users\ujwal\Downloads\AI_ASS_Project\traffic_video.mp4: 384x640 8 cars, 2 traffic lights, 44.0ms
video 1/1 (frame 88/1878) c:\Users\ujwal\Downloads\AI_ASS_Project\traffic_video.mp4: 384x640 8 cars, 44.4ms
video 1/1 (frame 89/1878) c:\Users\ujwal\Downloads\AI_ASS_Project\traffic_video.mp4: 384x640 7 cars, 106.5ms
video 1/1 (frame 90/1878) c:\Users\ujwal\Downloads\AI_ASS_Project\traffic_video.mp4: 384x640 8 cars, 62.4ms
video 1/1 (frame 91/1878) c:\Users\ujwal\Downloads\AI_ASS_Project\traffic_video.mp4: 384x640 8 cars, 47.2ms
video 1/1 (frame 92/1878) c:\Users\ujwal\Downloads\AI_ASS_Project\traffic_video.mp4: 384x640 7 cars, 69.6ms
video 1/1 (frame 93/1878) c:\Users\ujwal\Downloads\AI_ASS_Project\traffic_video.mp4: 384x640 9 cars, 90.0ms
video 1/1 (frame 94/1878) c:\Users\ujwal\Downloads\AI_ASS_Project\traffic_video.mp4: 384x640 7 cars, 51.9ms
video 1/1 (frame 95/1878) c:\Users\ujwal\Downloads\AI_ASS_Project\traffic_video.mp4: 384x640 10 cars, 43.1ms
video 1/1 (frame 96/1878) c:\Users\ujwal\Downloads\AI_ASS_Project\traffic_video.mp4: 384x640 8 cars, 43.0ms
video 1/1 (frame 97/1878) c:\Users\ujwal\Downloads\AI_ASS_Project\traffic_video.mp4: 384x640 10 cars, 42.3ms
video 1/1 (frame 98/1878) c:\Users\ujwal\Downloads\AI_ASS_Project\traffic_video.mp4: 384x640 10 cars, 63.3ms
video 1/1 (frame 99/1878) c:\Users\ujwal\Downloads\AI_ASS_Project\traffic_video.mp4: 384x640 7 cars, 55.6ms
video 1/1 (frame 100/1878) c:\Users\ujwal\Downloads\AI_ASS_Project\traffic_video.mp4: 384x640 9 cars, 47.4ms
video 1/1 (frame 101/1878) c:\Users\ujwal\Downloads\AI_ASS_Project\traffic_video.mp4: 384x640 11 cars, 46.0ms
video 1/1 (frame 102/1878) c:\Users\ujwal\Downloads\AI_ASS_Project\traffic_video.mp4: 384x640 10 cars, 68.3ms
video 1/1 (frame 103/1878) c:\Users\ujwal\Downloads\AI_ASS_Project\traffic_video.mp4: 384x640 7 cars, 67.6ms
video 1/1 (frame 104/1878) c:\Users\ujwal\Downloads\AI_ASS_Project\traffic_video.mp4: 384x640 7 cars, 45.1ms
video 1/1 (frame 105/1878) c:\Users\ujwal\Downloads\AI_ASS_Project\traffic_video.mp4: 384x640 8 cars, 49.4ms
video 1/1 (frame 106/1878) c:\Users\ujwal\Downloads\AI_ASS_Project\traffic_video.mp4: 384x640 7 cars, 81.9ms
video 1/1 (frame 107/1878) c:\Users\ujwal\Downloads\AI_ASS_Project\traffic_video.mp4: 384x640 1 person, 7 cars, 108.2ms
video 1/1 (frame 108/1878) c:\Users\ujwal\Downloads\AI_ASS_Project\traffic_video.mp4: 384x640 7 cars, 77.8ms
video 1/1 (frame 109/1878) c:\Users\ujwal\Downloads\AI_ASS_Project\traffic_video.mp4: 384x640 1 person, 7 cars, 56.1ms
video 1/1 (frame 110/1878) c:\Users\ujwal\Downloads\AI_ASS_Project\traffic_video.mp4: 384x640 1 person, 6 cars, 52.5ms
video 1/1 (frame 111/1878) c:\Users\ujwal\Downloads\AI_ASS_Project\traffic_video.mp4: 384x640 1 person, 7 cars, 53.0ms
video 1/1 (frame 112/1878) c:\Users\ujwal\Downloads\AI_ASS_Project\traffic_video.mp4: 384x640 2 persons, 5 cars, 45.4ms
video 1/1 (frame 113/1878) c:\Users\ujwal\Downloads\AI_ASS_Project\traffic_video.mp4: 384x640 1 person, 5 cars, 1 traffic light, 47.2ms
video 1/1 (frame 114/1878) c:\Users\ujwal\Downloads\AI_ASS_Project\traffic_video.mp4: 384x640 1 person, 5 cars, 1 traffic light, 45.1ms
video 1/1 (frame 115/1878) c:\Users\ujwal\Downloads\AI_ASS_Project\traffic_video.mp4: 384x640 1 person, 5 cars, 42.9ms
video 1/1 (frame 116/1878) c:\Users\ujwal\Downloads\AI_ASS_Project\traffic_video.mp4: 384x640 1 person, 7 cars, 47.8ms
video 1/1 (frame 117/1878) c:\Users\ujwal\Downloads\AI_ASS_Project\traffic_video.mp4: 384x640 1 person, 6 cars, 42.8ms
video 1/1 (frame 118/1878) c:\Users\ujwal\Downloads\AI_ASS_Project\traffic_video.mp4: 384x640 1 person, 6 cars, 42.2ms
video 1/1 (frame 119/1878) c:\Users\ujwal\Downloads\AI_ASS_Project\traffic_video.mp4: 384x640 2 persons, 5 cars, 1 skateboard, 44.8ms
video 1/1 (frame 120/1878) c:\Users\ujwal\Downloads\AI_ASS_Project\traffic_video.mp4: 384x640 1 person, 6 cars, 48.4ms
video 1/1 (frame 121/1878) c:\Users\ujwal\Downloads\AI_ASS_Project\traffic_video.mp4: 384x640 1 person, 7 cars, 1 skateboard, 49.8ms
video 1/1 (frame 122/1878) c:\Users\ujwal\Downloads\AI_ASS_Project\traffic_video.mp4: 384x640 1 person, 5 cars, 46.0ms
video 1/1 (frame 123/1878) c:\Users\ujwal\Downloads\AI_ASS_Project\traffic_video.mp4: 384x640 1 person, 5 cars, 42.4ms
video 1/1 (frame 124/1878) c:\Users\ujwal\Downloads\AI_ASS_Project\traffic_video.mp4: 384x640 4 cars, 42.6ms
video 1/1 (frame 125/1878) c:\Users\ujwal\Downloads\AI_ASS_Project\traffic_video.mp4: 384x640 1 person, 4 cars, 43.5ms
video 1/1 (frame 126/1878) c:\Users\ujwal\Downloads\AI_ASS_Project\traffic_video.mp4: 384x640 2 persons, 3 cars, 50.2ms
video 1/1 (frame 127/1878) c:\Users\ujwal\Downloads\AI_ASS_Project\traffic_video.mp4: 384x640 1 person, 3 cars, 1 traffic light, 49.2ms
video 1/1 (frame 128/1878) c:\Users\ujwal\Downloads\AI_ASS_Project\traffic_video.mp4: 384x640 5 cars, 1 traffic light, 48.2ms
video 1/1 (frame 129/1878) c:\Users\ujwal\Downloads\AI_ASS_Project\traffic_video.mp4: 384x640 6 cars, 47.9ms
video 1/1 (frame 130/1878) c:\Users\ujwal\Downloads\AI_ASS_Project\traffic_video.mp4: 384x640 6 cars, 44.1ms
video 1/1 (frame 131/1878) c:\Users\ujwal\Downloads\AI_ASS_Project\traffic_video.mp4: 384x640 5 cars, 44.3ms
video 1/1 (frame 132/1878) c:\Users\ujwal\Downloads\AI_ASS_Project\traffic_video.mp4: 384x640 5 cars, 45.8ms
video 1/1 (frame 133/1878) c:\Users\ujwal\Downloads\AI_ASS_Project\traffic_video.mp4: 384x640 6 cars, 42.8ms
video 1/1 (frame 134/1878) c:\Users\ujwal\Downloads\AI_ASS_Project\traffic_video.mp4: 384x640 6 cars, 42.4ms
video 1/1 (frame 135/1878) c:\Users\ujwal\Downloads\AI_ASS_Project\traffic_video.mp4: 384x640 5 cars, 47.6ms
video 1/1 (frame 136/1878) c:\Users\ujwal\Downloads\AI_ASS_Project\traffic_video.mp4: 384x640 7 cars, 42.6ms
video 1/1 (frame 137/1878) c:\Users\ujwal\Downloads\AI_ASS_Project\traffic_video.mp4: 384x640 4 cars, 44.4ms
video 1/1 (frame 138/1878) c:\Users\ujwal\Downloads\AI_ASS_Project\traffic_video.mp4: 384x640 5 cars, 41.6ms
video 1/1 (frame 139/1878) c:\Users\ujwal\Downloads\AI_ASS_Project\traffic_video.mp4: 384x640 6 cars, 45.1ms
video 1/1 (frame 140/1878) c:\Users\ujwal\Downloads\AI_ASS_Project\traffic_video.mp4: 384x640 6 cars, 43.1ms
video 1/1 (frame 141/1878) c:\Users\ujwal\Downloads\AI_ASS_Project\traffic_video.mp4: 384x640 6 cars, 42.6ms
video 1/1 (frame 142/1878) c:\Users\ujwal\Downloads\AI_ASS_Project\traffic_video.mp4: 384x640 7 cars, 47.8ms
video 1/1 (frame 143/1878) c:\Users\ujwal\Downloads\AI_ASS_Project\traffic_video.mp4: 384x640 7 cars, 49.4ms
video 1/1 (frame 144/1878) c:\Users\ujwal\Downloads\AI_ASS_Project\traffic_video.mp4: 384x640 5 cars, 1 traffic light, 48.6ms
video 1/1 (frame 145/1878) c:\Users\ujwal\Downloads\AI_ASS_Project\traffic_video.mp4: 384x640 5 cars, 43.1ms
video 1/1 (frame 146/1878) c:\Users\ujwal\Downloads\AI_ASS_Project\traffic_video.mp4: 384x640 4 cars, 43.9ms
video 1/1 (frame 147/1878) c:\Users\ujwal\Downloads\AI_ASS_Project\traffic_video.mp4: 384x640 4 cars, 46.2ms
video 1/1 (frame 148/1878) c:\Users\ujwal\Downloads\AI_ASS_Project\traffic_video.mp4: 384x640 4 cars, 1 traffic light, 45.3ms
video 1/1 (frame 149/1878) c:\Users\ujwal\Downloads\AI_ASS_Project\traffic_video.mp4: 384x640 4 cars, 43.9ms
video 1/1 (frame 150/1878) c:\Users\ujwal\Downloads\AI_ASS_Project\traffic_video.mp4: 384x640 4 cars, 53.5ms
video 1/1 (frame 151/1878) c:\Users\ujwal\Downloads\AI_ASS_Project\traffic_video.mp4: 384x640 4 cars, 44.9ms
video 1/1 (frame 152/1878) c:\Users\ujwal\Downloads\AI_ASS_Project\traffic_video.mp4: 384x640 4 cars, 1 traffic light, 43.6ms
video 1/1 (frame 153/1878) c:\Users\ujwal\Downloads\AI_ASS_Project\traffic_video.mp4: 384x640 4 cars, 89.9ms
video 1/1 (frame 154/1878) c:\Users\ujwal\Downloads\AI_ASS_Project\traffic_video.mp4: 384x640 4 cars, 45.2ms
video 1/1 (frame 155/1878) c:\Users\ujwal\Downloads\AI_ASS_Project\traffic_video.mp4: 384x640 4 cars, 47.2ms
video 1/1 (frame 156/1878) c:\Users\ujwal\Downloads\AI_ASS_Project\traffic_video.mp4: 384x640 4 cars, 42.8ms
video 1/1 (frame 157/1878) c:\Users\ujwal\Downloads\AI_ASS_Project\traffic_video.mp4: 384x640 4 cars, 46.0ms
video 1/1 (frame 158/1878) c:\Users\ujwal\Downloads\AI_ASS_Project\traffic_video.mp4: 384x640 4 cars, 42.8ms
video 1/1 (frame 159/1878) c:\Users\ujwal\Downloads\AI_ASS_Project\traffic_video.mp4: 384x640 4 cars, 1 traffic light, 43.2ms
video 1/1 (frame 160/1878) c:\Users\ujwal\Downloads\AI_ASS_Project\traffic_video.mp4: 384x640 4 cars, 42.7ms
video 1/1 (frame 161/1878) c:\Users\ujwal\Downloads\AI_ASS_Project\traffic_video.mp4: 384x640 4 cars, 1 traffic light, 45.1ms
video 1/1 (frame 162/1878) c:\Users\ujwal\Downloads\AI_ASS_Project\traffic_video.mp4: 384x640 4 cars, 42.4ms
video 1/1 (frame 163/1878) c:\Users\ujwal\Downloads\AI_ASS_Project\traffic_video.mp4: 384x640 4 cars, 41.7ms
video 1/1 (frame 164/1878) c:\Users\ujwal\Downloads\AI_ASS_Project\traffic_video.mp4: 384x640 4 cars, 47.7ms
video 1/1 (frame 165/1878) c:\Users\ujwal\Downloads\AI_ASS_Project\traffic_video.mp4: 384x640 4 cars, 44.9ms

In [25]:
results = model_yolo('traffic_video.mp4', stream=True)

vehicle_classes = ['car', 'truck', 'bus', 'motorcycle']

traffic_counts = []

for r in results:
    count = 0
    for box in r.boxes:
        class_id = int(box.cls[0])
        class_name = model_yolo.names[class_id]
        if class_name in vehicle_classes:
            count += 1
    traffic_counts.append(count)

print(traffic_counts[:20])
print(f"Processed {len(traffic_counts)} frames total")

video 1/1 (frame 1/1878) c:\Users\ujwal\Downloads\AI_ASS_Project\traffic_video.mp4: 384x640 1 person, 6 cars, 2 traffic lights, 1 fire hydrant, 64.8ms
video 1/1 (frame 2/1878) c:\Users\ujwal\Downloads\AI_ASS_Project\traffic_video.mp4: 384x640 1 person, 5 cars, 3 traffic lights, 2 fire hydrants, 49.5ms
video 1/1 (frame 3/1878) c:\Users\ujwal\Downloads\AI_ASS_Project\traffic_video.mp4: 384x640 1 person, 8 cars, 3 traffic lights, 1 fire hydrant, 48.8ms
video 1/1 (frame 4/1878) c:\Users\ujwal\Downloads\AI_ASS_Project\traffic_video.mp4: 384x640 2 persons, 7 cars, 5 traffic lights, 46.2ms
video 1/1 (frame 5/1878) c:\Users\ujwal\Downloads\AI_ASS_Project\traffic_video.mp4: 384x640 2 persons, 5 cars, 5 traffic lights, 1 fire hydrant, 46.2ms
video 1/1 (frame 6/1878) c:\Users\ujwal\Downloads\AI_ASS_Project\traffic_video.mp4: 384x640 1 person, 5 cars, 4 traffic lights, 1 fire hydrant, 46.0ms
video 1/1 (frame 7/1878) c:\Users\ujwal\Downloads\AI_ASS_Project\traffic_video.mp4: 384x640 1 person, 5 cars, 2 traffic lights, 45.6ms
video 1/1 (frame 8/1878) c:\Users\ujwal\Downloads\AI_ASS_Project\traffic_video.mp4: 384x640 3 persons, 5 cars, 2 traffic lights, 89.3ms
video 1/1 (frame 9/1878) c:\Users\ujwal\Downloads\AI_ASS_Project\traffic_video.mp4: 384x640 2 persons, 5 cars, 2 traffic lights, 46.6ms
video 1/1 (frame 10/1878) c:\Users\ujwal\Downloads\AI_ASS_Project\traffic_video.mp4: 384x640 1 person, 5 cars, 2 traffic lights, 1 fire hydrant, 46.8ms
video 1/1 (frame 11/1878) c:\Users\ujwal\Downloads\AI_ASS_Project\traffic_video.mp4: 384x640 5 cars, 2 traffic lights, 2 fire hydrants, 44.9ms
video 1/1 (frame 12/1878) c:\Users\ujwal\Downloads\AI_ASS_Project\traffic_video.mp4: 384x640 2 persons, 6 cars, 1 traffic light, 1 fire hydrant, 47.2ms
video 1/1 (frame 13/1878) c:\Users\ujwal\Downloads\AI_ASS_Project\traffic_video.mp4: 384x640 1 person, 7 cars, 2 traffic lights, 47.2ms
video 1/1 (frame 14/1878) c:\Users\ujwal\Downloads\AI_ASS_Project\traffic_video.mp4: 384x640 3 persons, 7 cars, 2 traffic lights, 48.0ms
video 1/1 (frame 15/1878) c:\Users\ujwal\Downloads\AI_ASS_Project\traffic_video.mp4: 384x640 1 person, 9 cars, 1 traffic light, 1 fire hydrant, 46.8ms
video 1/1 (frame 16/1878) c:\Users\ujwal\Downloads\AI_ASS_Project\traffic_video.mp4: 384x640 1 person, 7 cars, 1 fire hydrant, 46.6ms
video 1/1 (frame 17/1878) c:\Users\ujwal\Downloads\AI_ASS_Project\traffic_video.mp4: 384x640 1 person, 7 cars, 46.0ms
video 1/1 (frame 18/1878) c:\Users\ujwal\Downloads\AI_ASS_Project\traffic_video.mp4: 384x640 2 persons, 7 cars, 44.0ms
video 1/1 (frame 19/1878) c:\Users\ujwal\Downloads\AI_ASS_Project\traffic_video.mp4: 384x640 7 cars, 46.0ms
video 1/1 (frame 20/1878) c:\Users\ujwal\Downloads\AI_ASS_Project\traffic_video.mp4: 384x640 7 cars, 1 traffic light, 47.7ms
video 1/1 (frame 21/1878) c:\Users\ujwal\Downloads\AI_ASS_Project\traffic_video.mp4: 384x640 8 cars, 47.7ms
video 1/1 (frame 22/1878) c:\Users\ujwal\Downloads\AI_ASS_Project\traffic_video.mp4: 384x640 9 cars, 49.3ms
video 1/1 (frame 23/1878) c:\Users\ujwal\Downloads\AI_ASS_Project\traffic_video.mp4: 384x640 11 cars, 45.5ms
video 1/1 (frame 24/1878) c:\Users\ujwal\Downloads\AI_ASS_Project\traffic_video.mp4: 384x640 8 cars, 44.9ms
video 1/1 (frame 25/1878) c:\Users\ujwal\Downloads\AI_ASS_Project\traffic_video.mp4: 384x640 1 person, 8 cars, 47.2ms
video 1/1 (frame 26/1878) c:\Users\ujwal\Downloads\AI_ASS_Project\traffic_video.mp4: 384x640 9 cars, 46.1ms
video 1/1 (frame 27/1878) c:\Users\ujwal\Downloads\AI_ASS_Project\traffic_video.mp4: 384x640 11 cars, 50.0ms
video 1/1 (frame 28/1878) c:\Users\ujwal\Downloads\AI_ASS_Project\traffic_video.mp4: 384x640 13 cars, 1 traffic light, 46.3ms
video 1/1 (frame 29/1878) c:\Users\ujwal\Downloads\AI_ASS_Project\traffic_video.mp4: 384x640 10 cars, 47.1ms
video 1/1 (frame 30/1878) c:\Users\ujwal\Downloads\AI_ASS_Project\traffic_video.mp4: 384x640 10 cars, 46.3ms
video 1/1 (frame 31/1878) c:\Users\ujwal\Downloads\AI_ASS_Project\traffic_video.mp4: 384x640 11 cars, 45.8ms
video 1/1 (frame 32/1878) c:\Users\ujwal\Downloads\AI_ASS_Project\traffic_video.mp4: 384x640 10 cars, 47.6ms
video 1/1 (frame 33/1878) c:\Users\ujwal\Downloads\AI_ASS_Project\traffic_video.mp4: 384x640 11 cars, 47.2ms
video 1/1 (frame 34/1878) c:\Users\ujwal\Downloads\AI_ASS_Project\traffic_video.mp4: 384x640 8 cars, 45.3ms
video 1/1 (frame 35/1878) c:\Users\ujwal\Downloads\AI_ASS_Project\traffic_video.mp4: 384x640 9 cars, 44.6ms
video 1/1 (frame 36/1878) c:\Users\ujwal\Downloads\AI_ASS_Project\traffic_video.mp4: 384x640 1 person, 8 cars, 45.7ms
video 1/1 (frame 37/1878) c:\Users\ujwal\Downloads\AI_ASS_Project\traffic_video.mp4: 384x640 1 person, 6 cars, 46.9ms
video 1/1 (frame 38/1878) c:\Users\ujwal\Downloads\AI_ASS_Project\traffic_video.mp4: 384x640 6 cars, 47.0ms
video 1/1 (frame 39/1878) c:\Users\ujwal\Downloads\AI_ASS_Project\traffic_video.mp4: 384x640 6 cars, 47.0ms
video 1/1 (frame 40/1878) c:\Users\ujwal\Downloads\AI_ASS_Project\traffic_video.mp4: 384x640 2 persons, 7 cars, 45.1ms
video 1/1 (frame 41/1878) c:\Users\ujwal\Downloads\AI_ASS_Project\traffic_video.mp4: 384x640 1 person, 6 cars, 52.5ms
video 1/1 (frame 42/1878) c:\Users\ujwal\Downloads\AI_ASS_Project\traffic_video.mp4: 384x640 1 person, 9 cars, 46.6ms
video 1/1 (frame 43/1878) c:\Users\ujwal\Downloads\AI_ASS_Project\traffic_video.mp4: 384x640 5 cars, 45.5ms
video 1/1 (frame 44/1878) c:\Users\ujwal\Downloads\AI_ASS_Project\traffic_video.mp4: 384x640 5 cars, 1 traffic light, 44.4ms
video 1/1 (frame 45/1878) c:\Users\ujwal\Downloads\AI_ASS_Project\traffic_video.mp4: 384x640 5 cars, 48.1ms
video 1/1 (frame 46/1878) c:\Users\ujwal\Downloads\AI_ASS_Project\traffic_video.mp4: 384x640 6 cars, 46.6ms
video 1/1 (frame 47/1878) c:\Users\ujwal\Downloads\AI_ASS_Project\traffic_video.mp4: 384x640 6 cars, 48.5ms
video 1/1 (frame 48/1878) c:\Users\ujwal\Downloads\AI_ASS_Project\traffic_video.mp4: 384x640 1 person, 6 cars, 45.3ms
video 1/1 (frame 49/1878) c:\Users\ujwal\Downloads\AI_ASS_Project\traffic_video.mp4: 384x640 1 person, 6 cars, 45.0ms
video 1/1 (frame 50/1878) c:\Users\ujwal\Downloads\AI_ASS_Project\traffic_video.mp4: 384x640 1 person, 5 cars, 47.0ms
video 1/1 (frame 51/1878) c:\Users\ujwal\Downloads\AI_ASS_Project\traffic_video.mp4: 384x640 5 cars, 46.8ms
video 1/1 (frame 52/1878) c:\Users\ujwal\Downloads\AI_ASS_Project\traffic_video.mp4: 384x640 1 person, 5 cars, 49.1ms
video 1/1 (frame 53/1878) c:\Users\ujwal\Downloads\AI_ASS_Project\traffic_video.mp4: 384x640 1 person, 5 cars, 46.8ms
video 1/1 (frame 54/1878) c:\Users\ujwal\Downloads\AI_ASS_Project\traffic_video.mp4: 384x640 1 person, 6 cars, 47.8ms
video 1/1 (frame 55/1878) c:\Users\ujwal\Downloads\AI_ASS_Project\traffic_video.mp4: 384x640 1 person, 6 cars, 46.2ms
video 1/1 (frame 56/1878) c:\Users\ujwal\Downloads\AI_ASS_Project\traffic_video.mp4: 384x640 1 person, 5 cars, 46.0ms
video 1/1 (frame 57/1878) c:\Users\ujwal\Downloads\AI_ASS_Project\traffic_video.mp4: 384x640 1 person, 7 cars, 46.2ms
video 1/1 (frame 58/1878) c:\Users\ujwal\Downloads\AI_ASS_Project\traffic_video.mp4: 384x640 1 person, 7 cars, 47.7ms
video 1/1 (frame 59/1878) c:\Users\ujwal\Downloads\AI_ASS_Project\traffic_video.mp4: 384x640 1 person, 8 cars, 45.3ms
video 1/1 (frame 60/1878) c:\Users\ujwal\Downloads\AI_ASS_Project\traffic_video.mp4: 384x640 1 person, 7 cars, 44.8ms
video 1/1 (frame 61/1878) c:\Users\ujwal\Downloads\AI_ASS_Project\traffic_video.mp4: 384x640 5 cars, 45.8ms
video 1/1 (frame 62/1878) c:\Users\ujwal\Downloads\AI_ASS_Project\traffic_video.mp4: 384x640 5 cars, 47.0ms
video 1/1 (frame 63/1878) c:\Users\ujwal\Downloads\AI_ASS_Project\traffic_video.mp4: 384x640 1 person, 6 cars, 46.3ms
video 1/1 (frame 64/1878) c:\Users\ujwal\Downloads\AI_ASS_Project\traffic_video.mp4: 384x640 1 person, 6 cars, 46.0ms
video 1/1 (frame 65/1878) c:\Users\ujwal\Downloads\AI_ASS_Project\traffic_video.mp4: 384x640 1 person, 6 cars, 45.1ms
video 1/1 (frame 66/1878) c:\Users\ujwal\Downloads\AI_ASS_Project\traffic_video.mp4: 384x640 1 person, 7 cars, 46.9ms
video 1/1 (frame 67/1878) c:\Users\ujwal\Downloads\AI_ASS_Project\traffic_video.mp4: 384x640 2 persons, 7 cars, 47.0ms
video 1/1 (frame 68/1878) c:\Users\ujwal\Downloads\AI_ASS_Project\traffic_video.mp4: 384x640 2 persons, 7 cars, 45.4ms
video 1/1 (frame 69/1878) c:\Users\ujwal\Downloads\AI_ASS_Project\traffic_video.mp4: 384x640 2 persons, 6 cars, 100.1ms
video 1/1 (frame 70/1878) c:\Users\ujwal\Downloads\AI_ASS_Project\traffic_video.mp4: 384x640 2 persons, 6 cars, 49.2ms
video 1/1 (frame 71/1878) c:\Users\ujwal\Downloads\AI_ASS_Project\traffic_video.mp4: 384x640 2 persons, 5 cars, 47.5ms
video 1/1 (frame 72/1878) c:\Users\ujwal\Downloads\AI_ASS_Project\traffic_video.mp4: 384x640 2 persons, 5 cars, 51.8ms
video 1/1 (frame 73/1878) c:\Users\ujwal\Downloads\AI_ASS_Project\traffic_video.mp4: 384x640 2 persons, 4 cars, 49.5ms
video 1/1 (frame 74/1878) c:\Users\ujwal\Downloads\AI_ASS_Project\traffic_video.mp4: 384x640 1 person, 4 cars, 47.8ms
video 1/1 (frame 75/1878) c:\Users\ujwal\Downloads\AI_ASS_Project\traffic_video.mp4: 384x640 3 persons, 2 bicycles, 4 cars, 44.8ms
video 1/1 (frame 76/1878) c:\Users\ujwal\Downloads\AI_ASS_Project\traffic_video.mp4: 384x640 4 persons, 1 bicycle, 6 cars, 50.7ms
video 1/1 (frame 77/1878) c:\Users\ujwal\Downloads\AI_ASS_Project\traffic_video.mp4: 384x640 1 person, 1 bicycle, 6 cars, 45.8ms
video 1/1 (frame 78/1878) c:\Users\ujwal\Downloads\AI_ASS_Project\traffic_video.mp4: 384x640 4 persons, 1 bicycle, 7 cars, 47.5ms
video 1/1 (frame 79/1878) c:\Users\ujwal\Downloads\AI_ASS_Project\traffic_video.mp4: 384x640 1 person, 7 cars, 47.8ms
video 1/1 (frame 80/1878) c:\Users\ujwal\Downloads\AI_ASS_Project\traffic_video.mp4: 384x640 1 person, 6 cars, 47.6ms
video 1/1 (frame 81/1878) c:\Users\ujwal\Downloads\AI_ASS_Project\traffic_video.mp4: 384x640 6 cars, 46.1ms
video 1/1 (frame 82/1878) c:\Users\ujwal\Downloads\AI_ASS_Project\traffic_video.mp4: 384x640 2 persons, 7 cars, 45.6ms
video 1/1 (frame 83/1878) c:\Users\ujwal\Downloads\AI_ASS_Project\traffic_video.mp4: 384x640 1 person, 6 cars, 45.1ms
video 1/1 (frame 84/1878) c:\Users\ujwal\Downloads\AI_ASS_Project\traffic_video.mp4: 384x640 2 persons, 7 cars, 46.7ms
video 1/1 (frame 85/1878) c:\Users\ujwal\Downloads\AI_ASS_Project\traffic_video.mp4: 384x640 2 persons, 6 cars, 47.3ms
video 1/1 (frame 86/1878) c:\Users\ujwal\Downloads\AI_ASS_Project\traffic_video.mp4: 384x640 1 person, 6 cars, 52.5ms
video 1/1 (frame 87/1878) c:\Users\ujwal\Downloads\AI_ASS_Project\traffic_video.mp4: 384x640 8 cars, 2 traffic lights, 48.0ms
video 1/1 (frame 88/1878) c:\Users\ujwal\Downloads\AI_ASS_Project\traffic_video.mp4: 384x640 8 cars, 47.0ms
video 1/1 (frame 89/1878) c:\Users\ujwal\Downloads\AI_ASS_Project\traffic_video.mp4: 384x640 7 cars, 47.1ms
video 1/1 (frame 90/1878) c:\Users\ujwal\Downloads\AI_ASS_Project\traffic_video.mp4: 384x640 8 cars, 53.3ms
video 1/1 (frame 91/1878) c:\Users\ujwal\Downloads\AI_ASS_Project\traffic_video.mp4: 384x640 8 cars, 45.6ms
video 1/1 (frame 92/1878) c:\Users\ujwal\Downloads\AI_ASS_Project\traffic_video.mp4: 384x640 7 cars, 50.2ms
video 1/1 (frame 93/1878) c:\Users\ujwal\Downloads\AI_ASS_Project\traffic_video.mp4: 384x640 9 cars, 47.9ms
video 1/1 (frame 94/1878) c:\Users\ujwal\Downloads\AI_ASS_Project\traffic_video.mp4: 384x640 7 cars, 45.8ms
video 1/1 (frame 95/1878) c:\Users\ujwal\Downloads\AI_ASS_Project\traffic_video.mp4: 384x640 10 cars, 44.7ms
video 1/1 (frame 96/1878) c:\Users\ujwal\Downloads\AI_ASS_Project\traffic_video.mp4: 384x640 8 cars, 44.5ms
video 1/1 (frame 97/1878) c:\Users\ujwal\Downloads\AI_ASS_Project\traffic_video.mp4: 384x640 10 cars, 44.7ms
video 1/1 (frame 98/1878) c:\Users\ujwal\Downloads\AI_ASS_Project\traffic_video.mp4: 384x640 10 cars, 47.0ms
video 1/1 (frame 99/1878) c:\Users\ujwal\Downloads\AI_ASS_Project\traffic_video.mp4: 384x640 7 cars, 47.0ms
video 1/1 (frame 100/1878) c:\Users\ujwal\Downloads\AI_ASS_Project\traffic_video.mp4: 384x640 9 cars, 46.2ms
video 1/1 (frame 101/1878) c:\Users\ujwal\Downloads\AI_ASS_Project\traffic_video.mp4: 384x640 11 cars, 53.8ms
video 1/1 (frame 102/1878) c:\Users\ujwal\Downloads\AI_ASS_Project\traffic_video.mp4: 384x640 10 cars, 46.0ms
video 1/1 (frame 103/1878) c:\Users\ujwal\Downloads\AI_ASS_Project\traffic_video.mp4: 384x640 7 cars, 46.6ms
video 1/1 (frame 104/1878) c:\Users\ujwal\Downloads\AI_ASS_Project\traffic_video.mp4: 384x640 7 cars, 47.3ms
video 1/1 (frame 105/1878) c:\Users\ujwal\Downloads\AI_ASS_Project\traffic_video.mp4: 384x640 8 cars, 45.8ms
video 1/1 (frame 106/1878) c:\Users\ujwal\Downloads\AI_ASS_Project\traffic_video.mp4: 384x640 7 cars, 47.3ms
video 1/1 (frame 107/1878) c:\Users\ujwal\Downloads\AI_ASS_Project\traffic_video.mp4: 384x640 1 person, 7 cars, 83.7ms
video 1/1 (frame 108/1878) c:\Users\ujwal\Downloads\AI_ASS_Project\traffic_video.mp4: 384x640 7 cars, 47.7ms
video 1/1 (frame 109/1878) c:\Users\ujwal\Downloads\AI_ASS_Project\traffic_video.mp4: 384x640 1 person, 7 cars, 46.0ms
video 1/1 (frame 110/1878) c:\Users\ujwal\Downloads\AI_ASS_Project\traffic_video.mp4: 384x640 1 person, 6 cars, 46.9ms
video 1/1 (frame 111/1878) c:\Users\ujwal\Downloads\AI_ASS_Project\traffic_video.mp4: 384x640 1 person, 7 cars, 45.8ms
video 1/1 (frame 112/1878) c:\Users\ujwal\Downloads\AI_ASS_Project\traffic_video.mp4: 384x640 2 persons, 5 cars, 47.4ms
video 1/1 (frame 113/1878) c:\Users\ujwal\Downloads\AI_ASS_Project\traffic_video.mp4: 384x640 1 person, 5 cars, 1 traffic light, 46.7ms
video 1/1 (frame 114/1878) c:\Users\ujwal\Downloads\AI_ASS_Project\traffic_video.mp4: 384x640 1 person, 5 cars, 1 traffic light, 47.2ms
video 1/1 (frame 115/1878) c:\Users\ujwal\Downloads\AI_ASS_Project\traffic_video.mp4: 384x640 1 person, 5 cars, 45.0ms
video 1/1 (frame 116/1878) c:\Users\ujwal\Downloads\AI_ASS_Project\traffic_video.mp4: 384x640 1 person, 7 cars, 46.3ms
video 1/1 (frame 117/1878) c:\Users\ujwal\Downloads\AI_ASS_Project\traffic_video.mp4: 384x640 1 person, 6 cars, 44.9ms
video 1/1 (frame 118/1878) c:\Users\ujwal\Downloads\AI_ASS_Project\traffic_video.mp4: 384x640 1 person, 6 cars, 47.7ms
video 1/1 (frame 119/1878) c:\Users\ujwal\Downloads\AI_ASS_Project\traffic_video.mp4: 384x640 2 persons, 5 cars, 1 skateboard, 45.9ms
video 1/1 (frame 120/1878) c:\Users\ujwal\Downloads\AI_ASS_Project\traffic_video.mp4: 384x640 1 person, 6 cars, 47.2ms
video 1/1 (frame 121/1878) c:\Users\ujwal\Downloads\AI_ASS_Project\traffic_video.mp4: 384x640 1 person, 7 cars, 1 skateboard, 44.4ms
video 1/1 (frame 122/1878) c:\Users\ujwal\Downloads\AI_ASS_Project\traffic_video.mp4: 384x640 1 person, 5 cars, 46.8ms
video 1/1 (frame 123/1878) c:\Users\ujwal\Downloads\AI_ASS_Project\traffic_video.mp4: 384x640 1 person, 5 cars, 46.5ms
video 1/1 (frame 124/1878) c:\Users\ujwal\Downloads\AI_ASS_Project\traffic_video.mp4: 384x640 4 cars, 45.5ms
video 1/1 (frame 125/1878) c:\Users\ujwal\Downloads\AI_ASS_Project\traffic_video.mp4: 384x640 1 person, 4 cars, 45.9ms
video 1/1 (frame 126/1878) c:\Users\ujwal\Downloads\AI_ASS_Project\traffic_video.mp4: 384x640 2 persons, 3 cars, 46.5ms
video 1/1 (frame 127/1878) c:\Users\ujwal\Downloads\AI_ASS_Project\traffic_video.mp4: 384x640 1 person, 3 cars, 1 traffic light, 45.7ms
video 1/1 (frame 128/1878) c:\Users\ujwal\Downloads\AI_ASS_Project\traffic_video.mp4: 384x640 5 cars, 1 traffic light, 54.4ms
video 1/1 (frame 129/1878) c:\Users\ujwal\Downloads\AI_ASS_Project\traffic_video.mp4: 384x640 6 cars, 47.2ms
video 1/1 (frame 130/1878) c:\Users\ujwal\Downloads\AI_ASS_Project\traffic_video.mp4: 384x640 6 cars, 49.7ms
video 1/1 (frame 131/1878) c:\Users\ujwal\Downloads\AI_ASS_Project\traffic_video.mp4: 384x640 5 cars, 45.5ms
video 1/1 (frame 132/1878) c:\Users\ujwal\Downloads\AI_ASS_Project\traffic_video.mp4: 384x640 5 cars, 47.2ms
video 1/1 (frame 133/1878) c:\Users\ujwal\Downloads\AI_ASS_Project\traffic_video.mp4: 384x640 6 cars, 47.5ms
video 1/1 (frame 134/1878) c:\Users\ujwal\Downloads\AI_ASS_Project\traffic_video.mp4: 384x640 6 cars, 47.1ms
video 1/1 (frame 135/1878) c:\Users\ujwal\Downloads\AI_ASS_Project\traffic_video.mp4: 384x640 5 cars, 46.2ms
video 1/1 (frame 136/1878) c:\Users\ujwal\Downloads\AI_ASS_Project\traffic_video.mp4: 384x640 7 cars, 46.0ms
video 1/1 (frame 137/1878) c:\Users\ujwal\Downloads\AI_ASS_Project\traffic_video.mp4: 384x640 4 cars, 44.9ms
video 1/1 (frame 138/1878) c:\Users\ujwal\Downloads\AI_ASS_Project\traffic_video.mp4: 384x640 5 cars, 45.9ms
video 1/1 (frame 139/1878) c:\Users\ujwal\Downloads\AI_ASS_Project\traffic_video.mp4: 384x640 6 cars, 47.8ms
video 1/1 (frame 140/1878) c:\Users\ujwal\Downloads\AI_ASS_Project\traffic_video.mp4: 384x640 6 cars, 47.1ms
video 1/1 (frame 141/1878) c:\Users\ujwal\Downloads\AI_ASS_Project\traffic_video.mp4: 384x640 6 cars, 47.7ms
video 1/1 (frame 142/1878) c:\Users\ujwal\Downloads\AI_ASS_Project\traffic_video.mp4: 384x640 7 cars, 46.3ms
video 1/1 (frame 143/1878) c:\Users\ujwal\Downloads\AI_ASS_Project\traffic_video.mp4: 384x640 7 cars, 47.4ms
video 1/1 (frame 144/1878) c:\Users\ujwal\Downloads\AI_ASS_Project\traffic_video.mp4: 384x640 5 cars, 1 traffic light, 44.4ms
video 1/1 (frame 145/1878) c:\Users\ujwal\Downloads\AI_ASS_Project\traffic_video.mp4: 384x640 5 cars, 44.9ms
video 1/1 (frame 146/1878) c:\Users\ujwal\Downloads\AI_ASS_Project\traffic_video.mp4: 384x640 4 cars, 44.1ms
video 1/1 (frame 147/1878) c:\Users\ujwal\Downloads\AI_ASS_Project\traffic_video.mp4: 384x640 4 cars, 46.5ms
video 1/1 (frame 148/1878) c:\Users\ujwal\Downloads\AI_ASS_Project\traffic_video.mp4: 384x640 4 cars, 1 traffic light, 45.3ms
video 1/1 (frame 149/1878) c:\Users\ujwal\Downloads\AI_ASS_Project\traffic_video.mp4: 384x640 4 cars, 48.3ms
video 1/1 (frame 150/1878) c:\Users\ujwal\Downloads\AI_ASS_Project\traffic_video.mp4: 384x640 4 cars, 45.9ms
video 1/1 (frame 151/1878) c:\Users\ujwal\Downloads\AI_ASS_Project\traffic_video.mp4: 384x640 4 cars, 45.4ms
video 1/1 (frame 152/1878) c:\Users\ujwal\Downloads\AI_ASS_Project\traffic_video.mp4: 384x640 4 cars, 1 traffic light, 46.4ms
video 1/1 (frame 153/1878) c:\Users\ujwal\Downloads\AI_ASS_Project\traffic_video.mp4: 384x640 4 cars, 46.4ms
video 1/1 (frame 154/1878) c:\Users\ujwal\Downloads\AI_ASS_Project\traffic_video.mp4: 384x640 4 cars, 52.4ms
video 1/1 (frame 155/1878) c:\Users\ujwal\Downloads\AI_ASS_Project\traffic_video.mp4: 384x640 4 cars, 46.0ms
video 1/1 (frame 156/1878) c:\Users\ujwal\Downloads\AI_ASS_Project\traffic_video.mp4: 384x640 4 cars, 46.6ms
video 1/1 (frame 157/1878) c:\Users\ujwal\Downloads\AI_ASS_Project\traffic_video.mp4: 384x640 4 cars, 44.3ms
video 1/1 (frame 158/1878) c:\Users\ujwal\Downloads\AI_ASS_Project\traffic_video.mp4: 384x640 4 cars, 44.6ms
video 1/1 (frame 159/1878) c:\Users\ujwal\Downloads\AI_ASS_Project\traffic_video.mp4: 384x640 4 cars, 1 traffic light, 45.4ms
video 1/1 (frame 160/1878) c:\Users\ujwal\Downloads\AI_ASS_Project\traffic_video.mp4: 384x640 4 cars, 45.2ms
video 1/1 (frame 161/1878) c:\Users\ujwal\Downloads\AI_ASS_Project\traffic_video.mp4: 384x640 4 cars, 1 traffic light, 100.9ms
video 1/1 (frame 162/1878) c:\Users\ujwal\Downloads\AI_ASS_Project\traffic_video.mp4: 384x640 4 cars, 43.9ms
video 1/1 (frame 163/1878) c:\Users\ujwal\Downloads\AI_ASS_Project\traffic_video.mp4: 384x640 4 cars, 43.9ms
video 1/1 (frame 164/1878) c:\Users\ujwal\Downloads\AI_ASS_Project\traffic_video.mp4: 384x640 4 cars, 45.4ms
video 1/1 (frame 165/1878) c:\Users\ujwal\Downloads\AI_ASS_Project\traffic_video.mp4: 384x640 4 cars, 44.2ms
video 1/1 (frame 166/1878) c:\Users\ujwal\Downloads\AI_ASS_Project\traffic_video.mp4: 384x640 5 cars, 43.9ms
video 1/1 (frame 167/1878) c:\Users\ujwal\Downloads\AI_ASS_Project\traffic_video.mp4: 384x640 5 cars, 45.0ms
video 1/1 (frame 168/1878) c:\Users\ujwal\Downloads\AI_ASS_Project\traffic_video.mp4: 384x640 5 cars, 45.3ms
video 1/1 (frame 169/1878) c:\Users\ujwal\Downloads\AI_ASS_Project\traffic_video.mp4: 384x640 6 cars, 45.2ms
video 1/1 (frame 170/1878) c:\Users\ujwal\Downloads\AI_ASS_Project\traffic_video.mp4: 384x640 6 cars, 46.5ms

In [26]:
#phase 3
import numpy as np

avg_count = np.mean(traffic_counts)
print(f"Average vehicles per frame: {avg_count:.2f}")

if avg_count < 5:
    traffic_density_label = "Low"
elif avg_count < 10:
    traffic_density_label = "Medium"
else:
    traffic_density_label = "High"

print(f"Traffic density: {traffic_density_label}")

Average vehicles per frame: 4.86
Traffic density: Low

In [27]:
import joblib

model = joblib.load("accident_risk_model.pkl")
print(model.feature_names_in_)

['Traffic_Density' 'Speed_Limit' 'Number_of_Vehicles' 'Driver_Age' 'Driver_Experience' 'Weather_Foggy' 'Weather_Rainy' 'Weather_Snowy' 'Weather_Stormy' 'Road_Type_Highway' 'Road_Type_Mountain Road' 'Road_Type_Rural Road' 'Time_of_Day_Evening' 'Time_of_Day_Morning' 'Time_of_Day_Night' 'Driver_Alcohol_1.0'
 'Road_Condition_Icy' 'Road_Condition_Under Construction' 'Road_Condition_Wet' 'Vehicle_Type_Car' 'Vehicle_Type_Motorcycle' 'Vehicle_Type_Truck' 'Road_Light_Condition_Daylight' 'Road_Light_Condition_No Light']

In [28]:
print(df['Traffic_Density'].unique())
print(df['Traffic_Density'].describe())

[          1           2           0]
count    798.000000
mean       1.011278
std        0.770291
min        0.000000
25%        0.000000
50%        1.000000
75%        2.000000
max        2.000000
Name: Traffic_Density, dtype: float64

In [29]:
df_raw = pd.read_csv('dataset_traffic_accident_prediction1.csv')
print(df_raw['Traffic_Density'].unique())

[          1         nan           2           0]

In [31]:
# Phase 4: predict accident risk from video-derived traffic density

# Step 1: map our video label to the model's numeric scale (documented assumption)
density_map = {"Low": 0, "Medium": 1, "High": 2}
density_value = density_map[traffic_density_label]

# Step 2: start with sensible defaults from the training data for everything
# the video can't tell us (weather, road type, driver info, etc.)
input_row = X.mode().iloc[0].copy()  # most common value per column
for col in ['Speed_Limit', 'Number_of_Vehicles', 'Driver_Age', 'Driver_Experience']:
    input_row[col] = X[col].median()  # median is more sensible than mode for these

# Step 3: overwrite Traffic_Density with what we actually derived from the video
input_row['Traffic_Density'] = density_value

# Step 4: match the model's expected column order exactly
input_row = input_row[model.feature_names_in_]

# Step 5: predict
input_df = pd.DataFrame([input_row])
prob = model.predict_proba(input_df)[0][1]
prediction = 1 if prob >= 0.4 else 0  # your chosen threshold from Phase 1

print(f"Accident risk probability: {prob:.2f}")
print(f"Prediction: {'⚠️ ACCIDENT RISK' if prediction == 1 else '✅ LOW RISK'}")

Accident risk probability: 0.29
Prediction: ✅ LOW RISK

In [32]:
import json

defaults = X.mode().iloc[0].to_dict()
for col in ['Speed_Limit', 'Number_of_Vehicles', 'Driver_Age', 'Driver_Experience']:
    defaults[col] = float(X[col].median())

with open('defaults.json', 'w') as f:
    json.dump(defaults, f)
print("saved")

saved